# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "simulation"
title = "More Nodes"
authors = ["Sungmin Kim <kickthemoon0817@gmail.com>"]
keywords = ["node","graph","action graph node","more node"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.graph" = {}
"omni.graph.tools" = {}

# define the Python module that the extension provides
[[python.module]]
name = "isaacsim.nodes.more_nodes"

[settings]
exts."isaacsim.nodes.more_nodes".timeout = 5

